# Generated by Django 2.2.6 on 2019-10-05 21:58

import car_sales_app.models
from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.PositiveIntegerField(unique=True, verbose_name='Customer id')),
                ('Customer_Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=12, verbose_name='Customer gender')),
                ('Customer_Income_group', models.CharField(choices=[('1', '0- $25K'), ('2', '$25-$70K'), ('3', '>$70K')], max_length=12, verbose_name='Customer income group')),
                ('Customer_Region', models.CharField(choices=[('N', 'North'), ('S', 'South'), ('E', 'East'), ('W', 'West')], max_length=12, verbose_name='Customer region')),
                ('Customer_Marital_status', models.BooleanField(default=True, verbose_name='Customer marital status')),
            ],
            options={
                'ordering': ['customer_id'],
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_id', models.PositiveIntegerField(default=car_sales_app.models.Sales.increment_booking_number, verbose_name='Sales id')),
                ('purchased_date', models.DateField(default=django.utils.timezone.now, editable=False, verbose_name='purchased date')),
                ('fuel', models.CharField(choices=[('CN', 'CNG'), ('DI', 'Diesel'), ('PE', 'Petrol')], max_length=12, verbose_name='fuel')),
                ('Vehicle_segment', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=12, verbose_name='Vehicle segment')),
                ('Selling_Price', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('1000000.00'))], verbose_name='Selling price')),
                ('Power_steering', models.BooleanField(default=True, verbose_name='Power steering')),
                ('airbags', models.BooleanField(default=True, verbose_name='airbags')),
                ('sunroof', models.BooleanField(default=True, verbose_name='sunroof')),
                ('Matt_finish', models.BooleanField(default=True, verbose_name='Matt finish')),
                ('music_system', models.BooleanField(default=True, verbose_name='music system')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_sales_app.Customer', verbose_name='Customer')),
            ],
            options={
                'ordering': ['sales_id'],
            },
        ),
    ]
