# Generated by Django 2.2.6 on 2019-10-05 22:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('car_sales_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Customer_Region',
            new_name='Customer_region',
        ),
        migrations.AlterField(
            model_name='sales',
            name='purchased_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='purchased date'),
        ),
    ]
