# Generated by Django 2.2.6 on 2019-10-05 23:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('car_sales_app', '0002_auto_20191005_2219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Customer_Gender',
            new_name='customer_gender',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Customer_Income_group',
            new_name='customer_income_group',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Customer_Marital_status',
            new_name='customer_marital_status',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Customer_region',
            new_name='customer_region',
        ),
        migrations.RenameField(
            model_name='sales',
            old_name='Matt_finish',
            new_name='matt_finish',
        ),
        migrations.RenameField(
            model_name='sales',
            old_name='Power_steering',
            new_name='power_steering',
        ),
        migrations.RenameField(
            model_name='sales',
            old_name='Selling_Price',
            new_name='selling_price',
        ),
        migrations.RenameField(
            model_name='sales',
            old_name='Vehicle_segment',
            new_name='vehicle_segment',
        ),
        migrations.AlterField(
            model_name='sales',
            name='airbags',
            field=models.BooleanField(default=True, verbose_name='Airbags'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='fuel',
            field=models.CharField(choices=[('CN', 'CNG'), ('DI', 'Diesel'), ('PE', 'Petrol')], max_length=12, verbose_name='Fuel'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='music_system',
            field=models.BooleanField(default=True, verbose_name='Music system'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='purchased_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Purchased date'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sunroof',
            field=models.BooleanField(default=True, verbose_name='Sunroof'),
        ),
    ]
