# Generated by Django 2.2.6 on 2019-10-06 12:31

import car_sales_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_sales_app', '0004_auto_20191006_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='sales_id',
            field=models.PositiveIntegerField(default=car_sales_app.models.Sales.increment_booking_number, unique=True, verbose_name='Sales id'),
        ),
    ]
